first_number = input("Give me your first number : ")
second_number = input("Give me your secong number : ")
a = int(first_number)
b = int(second_number)
print("Thank you!")
print(first_number + " + " + second_number + " = " + str(a + b))
print(first_number + " - " + second_number + " = " + str(a - b))
print(first_number + " / " + second_number + " = " + str(a / b))
print(first_number + " * " + second_number + " = " + str(a * b))
